### ISSUE TITLE
Feature Request: Support Mismatch Retrieval Via FFI

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#132]
When writing the pact-net FFI integration, it's currently not possible to get any logging out of the verifier. The consumer side has had features added so that you can redirect logging to an in-memory sink and then retrieve the logs afterwards for inclusion in test output, but the verifier still logs directly to stdout as if it was invoked via a CLI.

The feature request is to extend the consumer logging support into the provider tests so that the verifier output (with mismatches etc) can also be included in test output.

This is currently a blocker for the new pact-net v4.0.0 release using the Rust core library instead of the Ruby integration.

**Comment by TimothyJones** [comment]
Pact-js needs the output on standard out, so supporting both would be ideal.

Is retrieving the logs the right way to implement this, though? It might be better for integration with reporting tools if the verifier result returned was structured.

**Comment by mefellows** [comment]
I think we need both.

i.e. we want the debug logs so we can have good bug reports etc., and we want structured values returned from the call so we can provide a better experience (e.g. in golang, I would convert them into subtests and you'd get granular breakdown of the actual tests being run).

**Comment by adamrodger** [comment]
Yeah if it could somehow return the individual checks so you can enumerate and run them individually (with proper output) that would be even more amazing. I'd have to look into how to do that with popular test frameworks in .Net because I've only done that sort of thing in xUnit.

At the moment in pact-net you just get one test per pact file which is very coarse grained.

The key thing is just getting those mismatches back though so you can include them when the provider test fails. At the moment it fails but you have no idea why because there's no output at all.

**Comment by TimothyJones** [comment]
We have the same in pact-js, one test runs one pact. 

I haven’t looked into it very seriously yet, but I think there are potentially options like talking to the reporting frameworks directly, or autogenerating a set of tests to fool the test framework into printing the output for us. Or, using the output modules from the test framework so that it looks like it’s a first class run (the jest test framework, for example, has a separate module that can be used to print diffs that look like they came from jest). I don’t know if a similar approach could work for .NET.

Anyway, as you said, that’s not exactly the core issue here :)

**Comment by mefellows** [comment]
Oh, so the log level is different for the verifier you're right. I don't think the FFI log methods fix this now that I think about it.

On mobile, but from memory it's controlled by the flag `--loglevel`.

**Comment by adamrodger** [comment]
Yeah the log level controls that, but it still only prints to stdout (which xUnit doesn't capture). I'm pretty sure it also prints all the colour escape sequences and stuff as well, so even if you could capture it I think it would look garbled.

What we really need is the log approach used for the mock server to be unified with the verifier now that they're in a common FFI library.

**Comment by mefellows** [comment]
Ah I forgot about that limitation in xUnit.

Agreed, I'll see if that's something that can be easily navigated but at some point we'll need to change the verifier interface as discussed above.

**Comment by martinisaksenprogleasing** [comment]
Is there any update on this? We are using .Net and we're looking at moving from a custom NuGet package we have been maintaining to v4.0.0, but the lack of output is a blocker for us. I am unable to troubleshoot why tests are failing. (The tests should pass, so I'm guessing it is a config issue, but no way of knowing right now).

**Comment by martinisaksenprogleasing** [comment]
FWIW, after some further testing, I am able to get output from my consumer creation tests, but not my verification tests. The NativeInterop.Very method does not provide any output details.

**Comment by mefellows** [comment]
@martinisaksenprogleasing you should be able to get output if you run from your terminal in the meantime. Because it logs to `stdout`. I've tested that whilst running https://github.com/DiUS/pact-workshop-dotnet-core-v3/ on my Mac. I assume it's the same.

It looks like 42be9eb8 landed last week. @uglyog do we need to migrate to the newer provider verifier methods for this to work, or is the second log extraction function (`pactffi_verifier_logs_for_provider`) that just uses the name of the provider sufficient?

**Comment by martinisaksenprogleasing** [comment]
I am on a Windows and I am not getting the output when running the Provider tests using that repo. (I have the preview version of .Net 6 installed. But I doubt that is the problem)

`PS C:\Code\pact-workshop-dotnet-core-v3\Provider> dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  provider -> C:\Code\pact-workshop-dotnet-core-v3\Provider\src\bin\Debug\netcoreapp3.1\provider.dll
  tests -> C:\Code\pact-workshop-dotnet-core-v3\Provider\tests\bin\Debug\net5.0\tests.dll
Test run for C:\Code\pact-workshop-dotnet-core-v3\Provider\tests\bin\Debug\net5.0\tests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210817-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.84]     tests.ProductTest.EnsureProviderApiHonoursPactWithConsumer [FAIL]
  Failed tests.ProductTest.EnsureProviderApiHonoursPactWithConsumer [468 ms]
  Error Message:
   PactNet.PactFailureException : The verification process failed, see output for errors
  Stack Trace:
     at PactNet.Native.NativePactVerifier.Verify(String args) in /Users/erikdanielsen/work/dius/pact-net/src/PactNet.Native/NativePactVerifier.cs:line 34
   at PactNet.Native.PactVerifier.Verify() in /Users/erikdanielsen/work/dius/pact-net/src/PactNet.Native/PactVerifier.cs:line 240
   at tests.ProductTest.EnsureProviderApiHonoursPactWithConsumer() in C:\Code\pact-workshop-dotnet-core-v3\Provider\tests\ProductTest.cs:line 46
  Standard Output Messages:
 Invoking the pact verifier with args:
 --file
 C:\Code\pact-workshop-dotnet-core-v3\pacts\ApiClient-ProductService.json
 --state-change-url
 http://127.0.0.1:9001/provider-states
 --provider-name
 ProductService
 --hostname
 127.0.0.1
 --port
 9001
 --filter-consumer
 ApiClient
 --loglevel
 trace



Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - tests.dll (net5.0)`

**Comment by uglyog** [comment]
`pactffi_verifier_logs_for_provider` will return all the logs that occurred when verifying a particular provider by name. It won't return the verifier output which shows the results, because that is not written via a logging framework.

Still need an API to get the results so the test framework can output it in an appropriate way. But it will need to use the Handle API, not the call where you pass in the command line.

**Comment by martinisaksenprogleasing** [comment]
@mefellows There seems to be compatibility issue with non-UTF-8 byte sequences in Rust's standard output on Windows. Could this be part of the issue? 

https://doc.rust-lang.org/std/io/fn.stdout.html

**Comment by adamrodger** [comment]
No the issue is that currently it's not implemented. We'll add support to
PactNet once it's stabilised in the FFI

**Comment by martinisaksenprogleasing** [comment]
@adamrodger My comment was in regards to the verification output working on Macs with the https://github.com/DiUS/pact-workshop-dotnet-core-v3 example. It shows the output during verification in the terminal, but I am unable to replicate that behavior locally on my Windows machine.

How were they able to get the verification output in the examples for that repo if it has not been implemented? (See step 4)

**Comment by adamrodger** [comment]
The FFI writes to stdout which appears to show up in some terminals on some
OSs, but that's more a fluke than by design. The design currently has no
implemented way of getting the output

**Comment by TimothyJones** [comment]
> The FFI writes to stdout which appears to show up in some terminals on some
OSs, but that's more a fluke than by design.

I don't think this is right. I didn't design the FFI, but by nature it will link into the running process. This means it will use the standard output of the process it links into, on all systems.

If there's something capturing or preventing that standard output from working when linked in .NET, I think it's a feature (or bug) of whatever is being used to link the ffi.
